apiVersion: v1
kind: Service
metadata:
  name: dev-db
  labels:
    app.kubernetes.io/name: dev-db
    app.kubernetes.io/component: postgres
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    app.kubernetes.io/name: dev-db
    app.kubernetes.io/component: postgres
