apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-hello-file-server
  labels:
    app: kube-hello-file-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-hello-file-server
  template:
    metadata:
      labels:
        app: kube-hello-file-server
    spec:
      serviceAccountName: kube-hello-file-server
      containers:
        - name: kube-hello-file-server
          image: ghcr.io/dgkim-lab/kube-hello-file-server:latest
          env:
            - name: BASE_PATH
              value: /files
          ports:
            - containerPort: 3000
              name: http
          volumeMounts:
            - name: files
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: files
          persistentVolumeClaim:
            claimName: kube-hello-file-server-files
