apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-hello-file-server-files
  labels:
    app: kube-hello-file-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
