apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingressgateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: 1.30.0
    helm:
      releaseName: istio-ingressgateway
      valuesObject:
        service:
          type: LoadBalancer
          ports:
            - name: status-port
              port: 15021
              targetPort: 15021
              protocol: TCP
            - name: http2
              port: 10080
              targetPort: 80
              protocol: TCP
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
