apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  tracing:
    - providers:
        - name: jaeger
      randomSamplingPercentage: 100
