apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/dgkim-lab/kube-hello-gitops.git
    targetRevision: HEAD
    path: infrastructure/kiali/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
