apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-hello-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dgkim-lab/kube-hello-gitops.git
    targetRevision: HEAD
    path: workloads/kube-hello-app/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-dev
  ignoreDifferences:
    - group: ""
      kind: Service
      name: kube-hello-app
      namespace: hello-dev
      jsonPointers:
        - /spec/selector
    - group: ""
      kind: Service
      name: kube-hello-app-preview
      namespace: hello-dev
      jsonPointers:
        - /spec/selector
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
